### ISSUE TITLE
Feature Request: Press a key to immediately drop the piece

### ISSUE THREAD

**Issue by codyhazelwood** [agentile1990/tetris-ts#2]
It would be cool if you could press Enter (or some other key) to immediately drop the piece.  It helps to speed things up when the game pace is slow at the beginning.

**Comment by agentile1990** [comment]
I started working on this today, but it's a little more tricky than anticipated. I published a new version last night that takes an options object as a parameter. It exposes some configuration options for the speed constant and the lines per level (speed increases after each level), which should help move things along. I was going to get a PR for that ready today. 

If I get out from under what I'm working on this afternoon, I can take another stab at it and see if I can get it done in time.
