### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Eimert** [agentile1990/tetris-ts#3]
Hey Andrew,

I'm new to web components. I've followed the [usage instructions at npmjs.com](https://www.npmjs.com/package/tetris-ts) and fiddled with different options:

|   |  const tetris = new Tetris( | const tetris = Tetris(  | 
|---|---|---|
|  **import Tetris from 'tetris-ts';** | [0] src/script/pages/app-home.ts(6,8): error TS1192: Module '"/home/eimert/dev/pwa-starter/node_modules/tetris-ts/dist/index"' has no default export. [0] src/script/pages/app-home.ts(19,27): error TS7006: Parameter 'data' implicitly has an 'any' type. [0] src/script/pages/app-home.ts(24,7): error TS6133: 'tetris' is declared but its value is never read.  | [0] src/script/pages/app-home.ts(6,8): error TS1192: Module '"/home/eimert/dev/pwa-starter/node_modules/tetris-ts/dist/index"' has no default export. [0] src/script/pages/app-home.ts(19,27): error TS7006: Parameter 'data' implicitly has an 'any' type. [0] src/script/pages/app-home.ts(24,7): error TS6133: 'tetris' is declared but its value is never read.  |
|  **import * as Tetris from 'tetris-ts';** | [0] src/script/pages/app-home.ts(19,27): error TS7006: Parameter 'data' implicitly has an 'any' type. [0] src/script/pages/app-home.ts(24,7): error TS6133: 'tetris' is declared but its value is never read. [0] src/script/pages/app-home.ts(24,20): error TS2351: This expression is not constructable. [0]   Type 'typeof import("/home/eimert/dev/pwa-starter/node_modules/tetris-ts/dist/index")' has no construct signatures.  | [0] src/script/pages/app-home.ts(19,27): error TS7006: Parameter 'data' implicitly has an 'any' type. [0] src/script/pages/app-home.ts(24,7): error TS6133: 'tetris' is declared but its value is never read. [0] src/script/pages/app-home.ts(24,16): error TS2349: This expression is not callable. [0]   Type 'typeof import("/home/eimert/dev/pwa-starter/node_modules/tetris-ts/dist/index")' has no call signatures.  |

Why is it complaining that the module 'has no default export'? Also feel free to check the (broken) [project](https://github.com/Eimert/Tetris-PWA) where the issue occurs.

**Comment by agentile1990** [comment]
Hi @Eimert, I apologize for the delay in my response. 

Although the project is written in TypeScript, I focused on packaging it in compiled JavaScript form for inclusion in another JavaScript web app. As such, I never tested including this in a TypeScript environment. 

I did pull down your repo and I confirmed that it indeed does not work. This project is using WebPack so I imagine something is not right with how it's being bundled for distribution. 

I will try to work on including this in a minimal TypeScript project to see if I can get it working. 

Vielen Dank! 

P.S. Cool idea pulling this into a PWA. Hopefully we can get it working for you.

**Comment by agentile1990** [comment]
Hi @Eimert, I wanted to let you know that I have published a v2.0.0 release to NPM which adds a default export for you do consume in your TypeScript PWA. 

I'm going to close this out for now. Please let me know if you get this working in your project. 
Good Luck!

**Comment by agentile1990** [comment]
Hi @Eimert, I'll be closing out this issue as its been sitting for some time. Please let me know if you need any further assistance and I'll be happy to help.
